from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(844, 499)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 310, 341, 131))
        self.stackedWidget.setObjectName("stackedWidget")
        self.with_key = QtWidgets.QWidget()
        self.with_key.setObjectName("with_key")
        self.decrypt_with_key = QtWidgets.QPushButton(parent=self.with_key)
        self.decrypt_with_key.setGeometry(QtCore.QRect(140, 90, 141, 41))
        self.decrypt_with_key.setObjectName("decrypt_with_key")
        self.get_key = QtWidgets.QLineEdit(parent=self.with_key)
        self.get_key.setGeometry(QtCore.QRect(0, 50, 281, 41))
        self.get_key.setObjectName("get_key")
        self.encrypt_with_key = QtWidgets.QPushButton(parent=self.with_key)
        self.encrypt_with_key.setGeometry(QtCore.QRect(0, 90, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.encrypt_with_key.setFont(font)
        self.encrypt_with_key.setObjectName("encrypt_with_key")
        self.print_key = QtWidgets.QPushButton(parent=self.with_key)
        self.print_key.setGeometry(QtCore.QRect(280, 50, 61, 41))
        self.print_key.setObjectName("print_key")
        self.stackedWidget.addWidget(self.with_key)
        self.no_key = QtWidgets.QWidget()
        self.no_key.setObjectName("no_key")
        self.encrypt_without_key = QtWidgets.QPushButton(parent=self.no_key)
        self.encrypt_without_key.setGeometry(QtCore.QRect(0, 40, 141, 61))
        self.encrypt_without_key.setObjectName("encrypt_without_key")
        self.decrypt_without_key = QtWidgets.QPushButton(parent=self.no_key)
        self.decrypt_without_key.setGeometry(QtCore.QRect(140, 40, 141, 61))
        self.decrypt_without_key.setObjectName("decrypt_without_key")
        self.stackedWidget.addWidget(self.no_key)
        self.output_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.output_text.setEnabled(True)
        self.output_text.setGeometry(QtCore.QRect(450, 40, 281, 311))
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.copy_text = QtWidgets.QPushButton(parent=self.centralwidget)
        self.copy_text.setGeometry(QtCore.QRect(730, 40, 61, 311))
        self.copy_text.setObjectName("copy_text")
        self.save_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_file.setGeometry(QtCore.QRect(450, 350, 281, 61))
        self.save_file.setObjectName("save_file")
        self.choose_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.choose_file.setGeometry(QtCore.QRect(310, 190, 61, 161))
        self.choose_file.setAcceptDrops(False)
        self.choose_file.setObjectName("choose_file")
        self.get_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.get_text.setGeometry(QtCore.QRect(30, 40, 281, 311))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        self.get_text.setFont(font)
        self.get_text.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.get_text.setObjectName("get_text")
        self.print_text = QtWidgets.QPushButton(parent=self.centralwidget)
        self.print_text.setGeometry(QtCore.QRect(310, 40, 61, 151))
        self.print_text.setObjectName("print_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(parent=self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menu = QtWidgets.QMenu(parent=self.menuFiles)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menuFiles)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.caesar = QtGui.QAction(parent=MainWindow)
        self.caesar.setCheckable(True)
        self.caesar.setChecked(True)
        self.caesar.setObjectName("caesar")
        self.verman = QtGui.QAction(parent=MainWindow)
        self.verman.setCheckable(True)
        self.verman.setObjectName("verman")
        self.vigenere = QtGui.QAction(parent=MainWindow)
        self.vigenere.setCheckable(True)
        self.vigenere.setObjectName("vigenere")
        self.base64 = QtGui.QAction(parent=MainWindow)
        self.base64.setCheckable(True)
        self.base64.setObjectName("base64")
        self.rus = QtGui.QAction(parent=MainWindow)
        self.rus.setCheckable(True)
        self.rus.setChecked(True)
        self.rus.setObjectName("rus")
        self.eng = QtGui.QAction(parent=MainWindow)
        self.eng.setCheckable(True)
        self.eng.setObjectName("eng")
        self.menu.addAction(self.caesar)
        self.menu.addAction(self.verman)
        self.menu.addAction(self.vigenere)
        self.menu.addAction(self.base64)
        self.menu_2.addAction(self.rus)
        self.menu_2.addAction(self.eng)
        self.menuFiles.addAction(self.menu.menuAction())
        self.menuFiles.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.decrypt_with_key.setText(_translate("MainWindow", "Расшифровать"))
        self.get_key.setPlaceholderText(_translate("MainWindow", "Ключ"))
        self.encrypt_with_key.setText(_translate("MainWindow", "Зашифровать"))
        self.print_key.setText(_translate("MainWindow", "CTRL+V"))
        self.encrypt_without_key.setText(_translate("MainWindow", "Зашифровать"))
        self.decrypt_without_key.setText(_translate("MainWindow", "Расшифровать"))
        self.output_text.setPlaceholderText(_translate("MainWindow", "Итоговый текст"))
        self.copy_text.setText(_translate("MainWindow", "CTRL+C"))
        self.save_file.setText(_translate("MainWindow", "Сохранить в файл"))
        self.choose_file.setToolTip(_translate("MainWindow", "Выбрать файл"))
        self.choose_file.setText(_translate("MainWindow", "Выбрать"))
        self.get_text.setPlaceholderText(_translate("MainWindow", "Текст для шифрования"))
        self.print_text.setText(_translate("MainWindow", "CTRL+V"))
        self.menuFiles.setTitle(_translate("MainWindow", "Настройки"))
        self.menu.setTitle(_translate("MainWindow", "Шифр"))
        self.menu_2.setTitle(_translate("MainWindow", "Язык"))
        self.caesar.setText(_translate("MainWindow", "Шифр Цезаря"))
        self.verman.setText(_translate("MainWindow", "Шифр Вермана"))
        self.vigenere.setText(_translate("MainWindow", "Шифр Виженера"))
        self.base64.setText(_translate("MainWindow", "BASE64"))
        self.rus.setText(_translate("MainWindow", "Русский"))
        self.eng.setText(_translate("MainWindow", "Английский"))
